slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    odom_frame: diff_drive/odom
    base_frame: diff_drive/base_link
    scan_topic: /scan
    mode: mapping
    publish_tf: true

    # ðŸ”§ resoluciÃ³n del mapa (fina)
    resolution: 0.05          # NO 0.5

    # ðŸ”§ frecuencia de actualizaciÃ³n del mapa
    map_update_interval: 0.1  # publica mapa cada 0.1 s (~10 Hz)

    # ðŸ”§ que actualice con movimientos pequeÃ±os
    minimum_travel_distance: 0.05   # antes 0.15 aprox
    minimum_travel_heading: 0.05    # antes 0.17 aprox

    # Ya los tienes bien:
    minimum_time_interval: 0.02     # acepta hasta ~50 Hz
    scan_queue_size: 10             # evita colas grandes
    transform_publish_period: 0.02
    transform_timeout: 0.5
    tf_buffer_duration: 20.0
