slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    odom_frame: diff_drive/odom
    base_frame: diff_drive/base_link
    scan_topic: /scan
    mode: mapping
    publish_tf: true
    resolution: 0.06              # 0.05 si quieres aún más “ligero”: 0.07 (menos detalle, más velocidad) 0.5
    minimum_time_interval: 0.02   # acepta hasta ~50 Hz; no filtres de más
    scan_queue_size: 10           # evita lag por colas enormes (mejor descartar que atrasar)
    transform_publish_period: 0.02
    transform_timeout: 0.5
    tf_buffer_duration: 20.0