slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    odom_frame: diff_drive/odom
    base_frame: diff_drive/base_link
    scan_topic: /scan
    mode: mapping
    publish_tf: true
    resolution: 0.05
    transform_timeout: 0.5
    tf_buffer_duration: 20.0
